version: '3.9'

services:
  postgres:
    image: postgres:9.6
    container_name: todo-postgres
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
  redis:
    image: redis:5.0.3-alpine
    container_name: todo-redis
    ports:
      - 6379:6379


volumes:
  postgres_data:
    driver: local
  pgadmin:
